print('Time you get back from Breakfast')
print("Time of first mile in seconds=")
x=(8*60+15)
print(x)

print('Time of next 3 miles at 7:12 pace in seconds =')
y=(7*60*3+12*3)
print(y)
print('Time of last mile')
z=(8*60+15)
print(z)
print('Total Time of Run in Sec')
print(y+x+z)